// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDOXd_p7_aDkh9TgqC-XTymYElRed0lZY',
    appId: '1:297142113621:web:5c07fb8e374193d9b44bdc',
    messagingSenderId: '297142113621',
    projectId: 'your-first-blog',
    authDomain: 'your-first-blog.firebaseapp.com',
    storageBucket: 'your-first-blog.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz8X3_BbQmHyWIfrbDlCFbY9gkW4XE8ts',
    appId: '1:297142113621:android:ac7643c1d3a24e61b44bdc',
    messagingSenderId: '297142113621',
    projectId: 'your-first-blog',
    storageBucket: 'your-first-blog.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3703aC6qCJltoZS6KVeypRH4y_sASN4A',
    appId: '1:297142113621:ios:50298cf5966f954eb44bdc',
    messagingSenderId: '297142113621',
    projectId: 'your-first-blog',
    storageBucket: 'your-first-blog.appspot.com',
    iosClientId: '297142113621-ocq4efcuq0h5cdvgujr3it1rd60hru51.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogapp',
  );
}
